### ISSUE TITLE
Release notes are far out of date

### ISSUE THREAD

**Issue by mmattel** [owncloud/docs-client-android#5]
After a discussion with @jesmrec we identified, that the android doc release notes https://github.com/owncloud/docs-client-android/blob/master/modules/ROOT/pages/appendices/release_notes.adoc have not been maintained post the release of 2.10 - at the moment we are shipping 2.18.x 

Referencing the changelog available at https://github.com/owncloud/android/tree/master/changelog, the release notes are present for 2.18.x but nothing lower.

1. Drop the release notes in docs completely
2. Only add the available ones from the changelog file, creates a missing delta
3. Try to recover the missing changelog info and provide it to docs so we can add it
4. ...

Suggestions welcomed

Note, in case we keep the docs android release notes, it may be a good idea to add an item at https://github.com/owncloud/android/blob/master/.github/ISSUE_TEMPLATE/release_template.md that the changelog delta should be transferred to docs - an issue would be sufficient

**Comment by michaelstingl** [comment]
> 1. Drop the release notes in docs completely

I‘d just add the link to the changelog, end remove the current entries. Calends generated changelogs are really good nowadays.

**Comment by mmattel** [comment]
@michaelstingl I have found the complete changelog (all releases) at https://github.com/owncloud/android/blob/master/CHANGELOG.md

Keeping your note and referencing to this file, PR is coming soon.
